name: gameStore Deploy

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Prepare WordPress Zip
        run: | 
          wp_LINK=$(cat wp-version-control.cfg)
          wget -O "./wordpress.zip" $wp_LINK

      - name: Prepare Plugins and theme zip
        run: zip -r wpcontent.zip plugins mu-plugins themes

      - name: Copy zip to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./wordpress.zip, ./wpcontent.zip"
          target: ${{ github.event_name == 'push' && '/dev/' || '/prod/' }}

      - name: Enable Maintenance Mode
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: ".maintenance"
          target: ${{ github.event_name == 'push' && '/dev/' || '/prod/' }}

      - name: Update WordPress Core
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            find "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}" -type f -name "*.php" ! -name "wp-config.php" -delete
            rm -r "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}/wp-admin/" "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}/wp-includes/"
            unzip -o "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}/wordpress.zip" -d "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}"
            mv "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}/wordpress/*" "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}/"
            rm -r "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}/wordpress/"

      - name: Update Plugins and Theme
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            rm -rf "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}/wp-content/plugins" "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}/wp-content/mu-plugins" "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}/wp-content/themes"
            unzip -o "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}/wpcontent.zip" -d "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}/wp-content/"


      - name: Disable Maintenance Mode
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            rm "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}/.maintenance"         
            rm "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}/wp-content.zip"         
            rm "${{ github.event_name == 'push' && '/dev/' || '/prod/' }}/wordpress.zip"         