name: gameStore Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare WordPress Files
        run: |
          wp_LINK=$(cat wp-version-control.cfg)
          wget -O "wordpress.zip" "$wp_LINK"
          rm -rf deploy
          mkdir -p deploy
          unzip -q wordpress.zip -d deploy
          rm -rf deploy/wordpress/wp-content/plugins deploy/wordpress/wp-content/mu-plugins deploy/wordpress/wp-content/themes
          mkdir -p deploy/wordpress/wp-content
          cp -R plugins mu-plugins themes deploy/wordpress/wp-content/

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: 21
          local-dir: deploy/wordpress/
          server-dir: /dev/
